name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag wsz_10_22:latest

    - name: Test Docker image
      run: |
        docker run -d -p 8000:8000 --name test-container wsz_10_22:latest
        sleep 10
        curl -f http://localhost:8000